name: first Workflow

on: push 

jobs: 
   first_job:
       runs-on: ubuntu-latest
       steps: 
       - name: checkout repo 
         uses: actions/checkout@v4
         
       - name: Welcome mesage 
         run: echo "welcome g"

       - name: list files 
         run:  ls   

       - name: read file
         run: cat README.md
